development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: loom_legacy_development

test:
  adapter: test

production:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: loom_legacy_production
