default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.root.join("storage/development.sqlite3") %>

test:
  <<: *default
  database: <%= Rails.root.join("storage/test.sqlite3") %>

production:
  <<: *default
  database: <%= Rails.root.join("storage/production.sqlite3") %>

