default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 
  host: localhost

development:
  <<: *default
  database: LOOMS-LEGACY

test:
  <<: *default
  database: LOOMS-LEGACY_test

production:
  <<: *default
  database: LOOMS-LEGACY_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
