default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 
  host: localhost

development:
  <<: *default
  database: LOOMS-LEGACY_6

test:
  <<: *default
  database: LOOMS-LEGACY_test

production:
  <<: *default
  database: looms_legacy_production-6
  username: ec2-user
  