default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Maasaa229$27
  host: localhost

development:
  <<: *default
  database: LOOMS-LEGACY_7

test:
  <<: *default
  database: LOOMS-LEGACY_test_1

production:
  adapter: postgresql
  encoding: unicode
  database: looms_legacy_production
  pool: 5
  username: ec2-user
  password: 'Maasaa229$27'
  host: localhost